site_name: Python Playground
site_description: A Python project template
site_url: https://linhai-fn.github.io/python_playground

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tooltips
    - content.tabs.link
    - announce.dismiss
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github-alt

repo_name: python_playground
repo_url: https://github.com/linhai-fn/python_playground

nav:
  - Home: index.md
  - API Documentation:
      - Group 1:
          - Main: api/main.md
      - Group 2:
          - Demo: api/demo.md
  - About: about.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - admonition
  # TODO: A MathJax configuration and the JavaScript runtime need to be included.
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
            show_signature_annotations: true
